---
- name: Playbook to configure ansible tower post installation
  hosts: localhost
  connection: local
  pre_tasks:
    - name: Include vars from tower_configs directory
      include_vars:
        dir: ./tower_configs
        ignore_files: [tower_config.yml.template]
        extensions: ["yml"]
      tags:
        - always
  roles:
    - {role: redhat_cop.tower_configuration.tower_settings, when: tower_settings is defined, tags: tower_settings}
    - {role: redhat_cop.tower_configuration.organizations, when: tower_organizations is defined, tags: organizations}
    - {role: redhat_cop.tower_configuration.labels, when: tower_labels is defined, tags: labels}
    - {role: redhat_cop.tower_configuration.users, when: tower_user_accounts is defined, tags: users}
    - {role: redhat_cop.tower_configuration.teams, when: tower_teams is defined, tags: teams}
    - {role: redhat_cop.tower_configuration.credentials, when: tower_credentials is defined, tags: credentials}
    - {role: redhat_cop.tower_configuration.credential_input_sources, when: tower_credential_input_sources is defined, tags: credential_input_sources}
    - {role: redhat_cop.tower_configuration.inventories, when: tower_inventories is defined, tags: inventories}
    - {role: redhat_cop.tower_configuration.projects, when: tower_projects is defined, tags: projects}
    - {role: redhat_cop.tower_configuration.inventory_sources, when: tower_inventory_sources is defined, tags: inventory_sources}
    - {role: redhat_cop.tower_configuration.hosts, when: tower_hosts is defined, tags: hosts}
    - {role: redhat_cop.tower_configuration.groups, when: tower_groups is defined, tags: inventories}
    - {role: redhat_cop.tower_configuration.job_templates, when: tower_templates is defined, tags: job_templates}
    - {role: redhat_cop.tower_configuration.workflow_job_templates, when: tower_workflows is defined, tags: workflow_job_templates}
    - {role: redhat_cop.tower_configuration.schedules, when: tower_schedules is defined, tags: schedules}
    - {role: redhat_cop.tower_configuration.notification_templates, when: tower_notifications is defined, tags: notifications}
    - {role: redhat_cop.tower_configuration.tower_role, when: tower_rbac is defined, tags: tower_role}
